templates = [
    {
        "Tech Giants": {
            "Meta": "META",
            "Apple": "AAPL",
            "Amazon": "AMZN",
            "Netflix": "NFLX",
            "Google": "GOOGL",
            "Microsoft": "MSFT",
        }
    },
    {
        "Financial Giants": {
            "JPMorgan Chase": "JPM",
            "Bank of America": "BAC",
            "Wells Fargo": "WFC",
            "Goldman Sachs": "GS",
            "Morgan Stanley": "MS",
            "Citigroup": "C",
        }
    },
    {
        "S&P 500 TOP 50": {
            "Apple": "AAPL",
            "Microsoft": "MSFT",
            "Google": "GOOGL",
            "Amazon": "AMZN",
            "NVIDIA": "NVDA",
            "Tesla": "TSLA",
            "Meta": "META",
            "Berkshire Hathaway": "BRK.B",
            "UnitedHealth": "UNH",
            "Johnson & Johnson": "JNJ",
            "JPMorgan Chase": "JPM",
            "Visa": "V",
            "Procter & Gamble": "PG",
            "Mastercard": "MA",
            "Home Depot": "HD",
            "Chevron": "CVX",
            "Coca-Cola": "KO",
            "Walmart": "WMT",
            "Bank of America": "BAC",
            "Pfizer": "PFE",
            "AbbVie": "ABBV",
            "Merck": "MRK",
            "PepsiCo": "PEP",
            "Intel": "INTC",
            "Cisco": "CSCO",
            "Verizon": "VZ",
            "AT&T": "T",
            "Comcast": "CMCSA",
            "Walt Disney": "DIS",
            "Netflix": "NFLX",
            "Adobe": "ADBE",
            "Salesforce": "CRM",
            "Oracle": "ORCL",
            "IBM": "IBM",
            "Broadcom": "AVGO",
            "Qualcomm": "QCOM",
            "Texas Instruments": "TXN",
            "AMD": "AMD",
            "Nike": "NKE",
            "Starbucks": "SBUX",
            "McDonald's": "MCD",
            "Caterpillar": "CAT",
            "Boeing": "BA",
            "3M": "MMM",
            "General Electric": "GE",
            "Exxon Mobil": "XOM",
            "ConocoPhillips": "COP",
        }
    },
]
